# Generated by Django 3.2 on 2022-06-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('meaasge', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(default='images/user.png', upload_to='user_image/')),
            ],
        ),
    ]
