# Generated by Django 3.2 on 2022-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('fromm', models.CharField(max_length=10)),
                ('to', models.CharField(max_length=16)),
                ('text', models.TextField(max_length=120)),
            ],
        ),
    ]
